### ISSUE TITLE
Problem about explanation(EX) model training.

### ISSUE THREAD

**Issue by zhuweipg99** [alon-albalak/D-REX#2]
Thank you for open-sourcing the code of your paper, nice work for dialogue relation extraction.
When I read your paper, I'm noticing you mentioned you train EX used policy gradient for unlabeled samples. It seems that the part (Policy gradient ) is not in the code you shared.
Can you share this part of the code if possible? I would be very grateful if it was possible.

**Comment by alon-albalak** [comment]
Thanks for checking out the project!

The code for the policy gradient is contained in train_drex.py
Lines 572-587 contain the computation of the re-ranking reward.
Lines 609-622 contain the computation of the leave-one-out reward that we use.

I hope that helps!
